@startuml IPC connection setup between remotediag and proxy__

title 01 IPC connection setup between remotediag and proxy

!pragma teoz true

skinparam BoxPadding 20
skinparam ParticipantPadding 20

autonumber
box "EP container\n" #lightYellow
    box "RemoteDiagProxy\n" #Application
        participant "<b>RemotediagProxy" as PROXY #Orange
        participant "<b>ProxyIpcClient" as CLI #Orange
        participant "<b>UnixSocketClient" as USC #Orange
    end box
end box

box "Internal container\n" #lightYellow
    box "RemoteDiag\n" #Application
        participant "<b>RemoteDiag" as RDG #Orange
        participant "<b>ProxyIpcServer" as SRV #Orange
        participant "<b>UnixSocketServer" as USS #Orange
    end box
end box



== Start server side (remotediag) ==
RDG->SRV: start()
SRV->USS: setFrameReceivedCallback(onFrameReceived)
SRV->USS: start()
USS->USS: createServerSocket()\nlisten(socketPath)

== Start client side (proxy) ==
PROXY->CLI: start()
CLI->USC: setFrameReceivedCallback(onFrameReceived)
CLI->USC: start()
USC->USS: connect(socketPath)
USS-->USC: accept() success

== Wait readiness ==
RDG->SRV: waitUntilReady(timeout)
SRV->USS: waitUntilConnected(timeout)
USS-->SRV: connected=true

PROXY->CLI: waitUntilReady(timeout)
CLI->USC: waitUntilConnected(timeout)
USC-->CLI: connected=true

note over SRV,CLI #White
Connection setup is complete after:
1) server listen() is active
2) client connect() succeeds
3) server accept() returns a client FD
end note

@enduml
